name = "RedFramework v1.0.9";
description = "RF - Version 1.0.9";
logo = "FRAMEWORK5.paa";
logoOver = "FRAMEWORK5.paa";
overviewPicture = "FRAMEWORK5.paa";
tooltip = "RF";
tooltipOwned = "RF Owned";
overview = "A collection of functions and configuration for quick mission editing.";
author = "RedBelette";